### Rota de Status da API
GET http://localhost:8080/

###

GET http://localhost:8080/test

### Cadastro de um novo usuário
# Primeiro, cadastre o usuário, como "Admin"
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "Admin",
    "password": "1234"
}

###

### Login de usuário
# Use o usuário "Kazbonfim" cadastrado para obter um token
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "1234"
}

###

### Acessar rota protegida
# Copie o token de acesso (accessToken) da resposta do login e cole aqui
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkbWluIiwibG9naW5BdCI6IjIwMjUtMDktMjZUMDA6MTA6NTkuOTkxWiIsImlhdCI6MTc1ODg0NTQ1OSwiZXhwIjoxNzU4ODQ5MDU5fQ.x8nvFhpgjV0kk841ZuI3Q5m98n45wdBXHVdix3GU4Jk